apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: kristianwindsor-cert
spec:
  secretName: kristianwindsor-cert
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: kristianwindsor.com
  dnsNames:
  - kristianwindsor.com
  acme:
    config:
    - dns01:
        provider: route53
        ingressClass: nginx
      domains:
      - kristianwindsor.com