apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: kristianwindsor-cert
spec:
  secretName: kristianwindsor-cert
  commonName: kristianwindsor.com
  dnsNames:
  - kristianwindsor.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer