apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kristianwindsor
  labels:
    app: kristianwindsor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kristianwindsor
    spec:
      containers:
        - name: kristianwindsor
          image: kristianwindsor/kristianwindsor.com
          ports:
            - containerPort: 80
          env:
            - name: SLACK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kristianwindsor-env
                  key: SLACK_TOKEN
          resources:
            requests:
              cpu: 5m