apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kristianwindsor-messages
  labels:
    app: kristianwindsor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi